name: restaurant_app
description: dicoding submission 1


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  pull_to_refresh_flutter3: ^2.0.1
  fluttertoast: ^8.1.3
  flutter_rating_bar: ^4.0.1
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.1.0
  lottie: ^2.2.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/lottie/food_splash.json
    - assets/json/restaurant.json


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf

